import Boon from "./gw2-ui/Boon.astro";
import Skill from "./gw2-ui/Skill.astro";
import Trait from "./gw2-ui/Trait.astro";

export const components = {
  Advanced: () => undefined,
  Attribute: () => undefined,
  Beginner: () => undefined,
  BuildLink: () => undefined,
  Boon,
  Card: () => undefined,
  Character: () => undefined,
  CharacterWithAr: () => undefined,
  Condition: () => undefined,
  Control: () => undefined,
  Divider: () => undefined,
  Effect: () => undefined,
  Grid: () => undefined,
  GridItem: () => undefined,
  Information: () => undefined,
  Instability: () => undefined,
  Item: () => undefined,
  Label: () => undefined,
  Skill,
  Skills: () => undefined,
  SpecialActionKey: () => undefined,
  Specialization: () => undefined,
  Tab: () => undefined,
  Tabs: () => undefined,
  Trait,
  Traits: () => undefined,
  Uncategorized: () => undefined,
  Video: () => undefined,
  Warning: () => undefined,
  Weapons: () => undefined,
};
