import {
  Profession,
  Boon,
  Attribute,
  Condition,
  Item,
  Skill,
  Trait,
  ControlEffect,
  CommonEffect,
  MistlockInstability,
} from "@gw2-ui/components";

const components = {
  hr: () => undefined,
  li: () => undefined,
  ol: () => undefined,
  a: () => undefined,
  table: () => undefined,
  Achievement: () => undefined,
  Augmentation: () => undefined,
  Advanced: () => undefined,
  Attribute,
  Beginner: () => undefined,
  BuildLink: () => undefined,
  Boon,
  Boss: () => undefined,
  Card: ({ children }) => <div className="bg-slate-600">{children}</div>,
  Character: () => undefined,
  CharacterWithAr: () => undefined,
  ChallengeMode: () => undefined,
  Composition: () => undefined,
  Condition,
  Control: ControlEffect,
  Divider: () => undefined,
  Effect: CommonEffect,
  GifPlayer: () => undefined,
  Grid: () => undefined,
  GridItem: () => undefined,
  Image,
  Information: () => undefined,
  InformationBlock: () => undefined,
  Instability: MistlockInstability,
  Item,
  Label: () => undefined,
  NormalMode: () => undefined,
  ProfessionVideo: () => undefined,
  Skill,
  Skills: () => undefined,
  SpecialActionKey: () => undefined,
  Specialization: Profession,
  Tab: () => undefined,
  Tabs: () => undefined,
  Trait,
  Traits: () => undefined,
  Uncategorized: () => undefined,
  Video: () => undefined,
  Warning: () => undefined,
  Weapons: () => undefined,
};

export default components;
